export const DISABLE_BLUETOOTH = 'DISABLE_BLUETOOTH'
export const ENABLE_BLUETOOTH = 'ENABLE_BLUETOOTH'

export const OPEN_DATABASE = 'OPEN_DATABASE'
export const CLOSE_DATABASE = 'CLOSE_DATABASE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

export const UPDATE_SALE = 'UPDATE_SALE'

export const UPDATE_STYLIST = 'UPDATE_STYLIST'
